language: android
android:
  components:
    # travis/android: https://docs.travis-ci.com/user/languages/android/
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by the project
    - build-tools-28.0.3
    # The SDK version used to compile the project
    - android-28

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
before_install:
  - yes | sdkmanager "platforms;android-28" "platform-tools" "tools"
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.android/build-cache"
before_script:
  - export VERSION_TO_BUILD="$TRAVIS_TAG"
  - export PATH="$ANDROID_HOMEtools/bin:$PATH"
script:
  - "./gradlew --stacktrace check --no-daemon"
after_success:
  - ./scripts/deploy-snapshot.sh
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    file: deeplink/build/outputs/apk/android-deeplink-${VERSION_TO_BUILD}-release.aar
    skip_cleanup: true
    script: ./gradlew clean build
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: ./script/deploy-release.sh
    on:
      tags: true

env:
  global:
    - secure: ZuVZxYoRwwilDqDOLv4sl6+a9Na4FjYyHJfrWyzLDjZa1eFjRKBpJ3I0fM3GKAjTUNd71Wk3Rt8WROsQMyM9ua7Ge8lJMCJwtqFLwGDH677qyw6wH4SLXfdQE2qdTsQQjWZPGKIO3hgPQcZWkWYjLyddx1yTgQ+ttncXRaq+J7yxR4zsrSw7hBAsAtxFLMGTVJxGlsAmSKahjXwbWRhnEZs6G7dMp6xoRYqLuR1EiyugFgyZL9vZyTBoOUbUXgDBFn5sDLQFLhkQfImhz+Pf6lzjbwHX/BFXc4B7v9PTcNmJtGp8mKlPDHWa/E88epAz1UQMLPewVfaCsAcSBL5YYa+0UqSDcI6HbOzzVWlJguWeSaYceUnLrkDJJjInvDSGAuPPxJS8kR0h4JUThItgSQdG59CLSaZsh+BUEt7lgftOegUy2hr1qExj0FStcC6M5iBlO1lvvtOyXeHPf7T3iOHqtRS6oEUsPo2ePEQaOdCJOM/UtL+sIvjuq1Q0fGPhZw54Svd4xBRAMsMJ9PROvmdj9a0Z7TaP0nMj3FkRlQhpvhJfXsACuvnvjd4TS6sFPgnJR+/wPv0+KLu7k56H7wx23AHn+Xz1Z2rPam+GlYilucDdrc9UEZQxyg19ncD0csgRhO92yFWWpvaUhgJz8mb3XXodPbiv2P1hrri/gUc=
    - secure: FjeExO22g78joTnZunuZg4ksWKTupFR8iJqv6m7NM6RGyjeXuXHccfBvBHlnI/6stlac7o1faTbH1obztYw44ufqMZ1ncwTrDmxy5n8ja1TY9etMfaf2m0SYChkRE3HGYmjzg8i+jce+fuMbDeSBuFjZ4QeY0bTxEZ52taolnWPNPGUn+J7PUVWEwiqSYQ3c2HtPsEb+ZhhSg0PK5d/hByON0sOz14nxObbYwu8Ca5JqYDZBRMwkkYPLalOVHQv8U88gU7r2Y3qERFVE/SM9+5pPyFe1MWzn71Xp76eIErlkey5KJdzs4mViErn4rgBOv46uCDdlt8aGseNynaI80EpZBPhcbc+Y4Bbt2PJ44ZUENwzMSDfz5SUk4h+yDELeru+3WHEFFZAJcJi9JJHVjZBs2zpRen34tB317cR7WSSA9A7eJY+rmJ1mfWfAlu/BzsPQewaKTsOJ6oBoH3oL4bL182kmApkCvF7g2ysBYvDwO8HQehkyVDsJuLhRhAJHwjLSPLA3A9PX76PdYvQPdz0WXUw+I6oplwpzIavNVTdvCiZfDa+YLbU6cc90RDjLZn5GvhEX+sb8eOU+xe+nkrh74+cMJMk/f7z40Gw7NUb+T3lVteH4IoA8rbTRbyr/0bVKrOc8CDYz74exsLy/MoQqkPI8bclaw1ENF50Fukk=
    - secure: B89rJixtdiaiSR0cCKLTwnzwxYjS4LJtMu2L68BWIJHilEWhfpUQTNFTeWqU+WnWn4mUzsYW+bA1NZNX7cCpQzWCJOtM9WY2fZUqRIrRDErIcQVPSUVvRopl6nz6ovD1ZJKT+gHecSKZvyp7QHZ9mc0qWdx0b75UpNiiSq5vHwxUDLmd9Ti2FQ6fFfp/cDPp8NKXbB5YxcK71jPqqjVdYSYjAXvsK11hK1wnw1wnbEJs49kMu+DWDf5kPYIxc3yX2kf6B2QktZx1YYmXa9NMykW+Cj3Gdkwxotm4kMpHigEpMYvYK3htSjKILAJrRrMFQi+1nDuTBQoOIstFK6VsgsHAKqOR6OTY4hxCPDtn7wLEbeNV/UTIHBqamzOqk4la4tioCmK58J1LnOzpEXACmtO0KPvZpZ8aTiVbOLHoa0rUeLpIFwxw4SPjVHVupls0lELr+EoPhqx/gxm8OxDU4iODVLAcVwOtAHBPLNlte3Pyz+fgKOsb7Ant7nXQ+0JM3nDL0zZXNQrU/A87XyWwzVaoLERrDjYYXy19TAi28MOpNAtka4LFsTJQJpB7r6uTUKaaC1NCzJwYTAwPza5BuY6xLQEsGYG6vH9PoqdntSAHWx2Bg/lpH++8QvSbD+7n58wvBkSCExybmS6oNE3kLBs3lv5vgn5Mzvi1sNoPIFs=
