language: android
android:
  components:
    # travis/android: https://docs.travis-ci.com/user/languages/android/
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by the project
    - build-tools-28.0.3
    # The SDK version used to compile the project
    - android-28

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
before_install:
  - yes | sdkmanager "platforms;android-28" "platform-tools" "tools"
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.android/build-cache"
script:
  - "./gradlew --stacktrace check --no-daemon"
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./scripts/deploy-snapshot.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: ./script/deploy-release.sh
    on:
      tags: true

env:
  global:
    - secure: YvcpKhpqHvHhjlFIXqx3gWfx9yeGD2Aowl/UpkVc7Jasl+pDe9E0CeFgcGsMjlC6DQWZLpd0K/UuqZhEnH2gtNDJx/f2bm3BQfjmmQXqPMBKx2PHt5rd2vH0IqVYyRwAk9KFUixh67HI+i2npOq3wB3Hm+s/vn8N3znLnPlEEDkfCZ4yJHSGt6uja5mittryW25AjYVUli8EdNnxtkhcrjLG8TK0SiybpkUp8AgxTEFcmGTK1rugAha+6bBW7J4rAFkac+Gwq2Wejr9n9IY6SPd1FsIFt7/YPjqo7jGQFNxUwrewv7NueL+3aChqogqYpG6RlVFjBRlExppHM8eD/X82v/525tOPws6K6IXj3pM3zDyJ49468ktYVtSXOLUw9d8lAFBsUrU9d1BKMoCVL/CFC4+z+UikKdAvPHpUdi9YmTmTCA5WkDcr4m/Np5gTGFFG3ZSXD3Q6n5YVKSD0ZSDhEcE57OS0lVI0tR9aaOsL6sgaEOc/6LpAV0xJBm5XqhEIiZkYwmcnx2r3+g1k6SDwQI7w/3l6mr2Za7eFiSbC2I4Vx+9VF3D73NAshVo370yfcZD4bBfSVRypJGuMs3CMsOKarVu4ea5q6PrN9WwxSdbKlF2LcZEpYyy39PLp57TmKqqyp604TGO66kFcsAfOOt0HE27/gtLroM+aIjY=
    - secure: CsH+n6AfxlFD8Ei4vx2ztyxxpbNCsHeYb9TA/4gI2GWjXvqV/qVfcJUa+iv1fDd1Bhl6/j6rR3xiaQjknR49xSlmWnI6zdE25HrGFU0PV/QgPOIJu4JWevkoytRajNz93D9eUHh6EuyGv8qxIhsr9JEeo7CKXtDhQIb698OImjdhtgjC7Y55ESavwMzTgNTrhEquk3ZO1hYwOLX60/lq6vfuEWtfkZd4RdSmcwYqV4FREPUBaDm1oY0Yjz5idyTzdCEEfGuuGb2EzvuDI+VY4zMkxt776YT0DHHe+VsbycAXEmid+hRgXXDCLEaoUuP8gwaLWRD5gfSINRPfpPODJJ4Z0m9CcNn7I2f6khGNIFAnrfimU6ox61ejw7H1KCPqYcUV9BjAKqGymgojCzETBtaRZaXN3WwDqmoPOur70IXC4+Th7p3JeOie1HZCE7Rq0hwepIh1Mzt4xa4AE0lh/Fh2X6JiVV4r3xIsuBD9glJOAcNSPvveAocTurHJGSlMHL0KjpgLYVVsyNcNYgQxCz4C0HHVsTdgHahKbGBvTb9v+NOqwdgNzhvmFpmxCcITjj2/+XT62mohwmNLcgBeJbK1Mf9iOH7T+R3a8Ko4Rpi2Go/+nQN9zZxSk7tFkQHIZpZiuhIapSGaZz1TdHZciH04DaJyQP8MONoJJnmiLtc=