/*
 * Copyright (c) 2019.  The HelloFresh Android Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath(libs.agp)
        classpath(libs.kotlinGradle)
        classpath(libs.unmockGradle)
    }
}

plugins {
    alias(libs.plugins.detekt)
    alias(libs.plugins.junitJacoco)
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}

detekt {
    buildUponDefaultConfig = true
    reports.txt.enabled = false
    reports.html.enabled = false
}

junitJacoco {
    jacocoVersion = libs.versions.jacoco.get()
    excludes = listOf(
        // Android
        "**/R.class",
        "**/R$*.class",
        "**/BuildConfig.*",
        "**/Manifest*.*",
        // Others
        "**/*\$Companion.class",
        "**/*Lambda$*.*", // Jacoco can not handle several "$" in class name.
        "**/*$*$*.*" // Anonymous classes generated by kotlin)
    )
}
