object Excludes {

    val jacocoAndroid = listOf(
        // Android
        "**/R.class",
        "**/R$*.class",
        "**/BuildConfig.*",
        "**/Manifest*.*",
        // Others
        "**/*\$Companion.class",
        "**/*Lambda$*.*", // Jacoco can not handle several "$" in class name.
        "**/*$*$*.*" // Anonymous classes generated by kotlin)
    )
}